---
- name: restart web server
  service:
    name: "{{ wordpress_packages.web_service }}"
    state: restarted

- name: restart database
  service:
    name: "{{ wordpress_packages.db_service }}"
    state: restarted

- name: reload web server
  service:
    name: "{{ wordpress_packages.web_service }}"
    state: reloaded